version: '3.4'
services:
  mongo_database:
    image: mongo:latest
    restart: always
    ports:
      - '2717:27017'
    networks:
      - node-mongo-app
    volumes:
      - mongo_database_data:/data/db
  node-server:
    build: .
    restart: always
    environment:
      DATABASE_URL_DEV: mongodb://mongo_database:27017
      DATABASE_NAME: my_db
    command: 'node ./build/src/index.js'
    ports:
      - '4000:4000'
    depends_on:
      - mongo_database
    networks:
      - node-mongo-app
networks:
  node-mongo-app:
    driver: bridge
volumes:
  mongo_database_data:
    driver: local
