version: '3.4'
services:
  mongo_database:
    image: mongo:latest
    restart: always
    ports:
      - '2717:27017'
    networks:
      - node-mongo-app
    volumes:
      - mongo_database_data:/data/db
  node_server:
    build: .
    restart: always
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn run dev
    environment:
      PORT: 4000
      DATABASE_URL_DEV: mongodb://mongo_database:27017
      DATABASE_NAME: my_db
    depends_on:
      - mongo_database
    networks:
      - node-mongo-app
networks:
  node-mongo-app:
    driver: bridge
volumes:
  mongo_database_data:
    driver: local
