### Health check
GET http://localhost:4000/api


### Sign up user
POST http://localhost:4000/api/signup
Content-Type: application/json

{
  "name": "Nipun",
  "email": "ravisara.dev@gmail.com",
  "password": "password@123",
}
